### ISSUE TITLE
[Component] Tag

### ISSUE THREAD

**Issue by PreAgile** [codestates/SearchCaffe_client#29]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Tag를 누를때 해당 Tag에 속한 Cafe들만 화면에 뿌려주는 기능 구현.
### TODO
1. [x] CafeInfo 쪽에 Tag에 관련된 칼럼 추가
2. [x] CafeInfo에 데이터를 넣고 해당 데이터들을 클라쪽에 불러오기
3. [x] 불러온 데이터들을 분류하기
### Estimated time
> Pick one
### Labels
- Estimated time: `E: 5h`
- Group : `client`, `server`
- Sprint: `Sprint1`
- Urgency: `Middle`
