### ISSUE TITLE
[Component] Comment에 따른 firebase 작업

### ISSUE THREAD

**Issue by PreAgile** [codestates/SearchCaffe_client#47]
### ISSUE
- Group:  `client`
- Type: `feature`, 
- Detail: 여러가지 사진들을 업로드, 유저 코멘트와 카페에 대한 평점을 올린뒤 firebase에 연동해서 firbase.storage and firebase.store에 저장
### TODO
1. [x] 사진들을 업로드시 firebase.store에 저장
2. [x] 저장한 store에 따른 url을 cafeComment필드에 추가
3. [x] 유저가 작성한 이미지와 내용, 별점까지 firebase.store에 저장
### Estimated time
> Pick one
### Labels
- Estimated time: `E: 17`
- Group : `client`, `server`
- Sprint: `Sprint_2`
- Urgency: `High`
