### ISSUE TITLE
[Component] Comment 수정 Bug Fix

### ISSUE THREAD

**Issue by PreAgile** [codestates/SearchCaffe_client#73]
### ISSUE
- Group:  `client`
- Type: `feature`, 
- Detail: 
### TODO
1. [x] Star Bug Fix
2. [x] Picture Bug Fix => 해당 부분은 경섭님한테 요청함
3. [x] Tag Bug Fix
### Estimated time
> Pick one
### Labels
- Estimated time: `E: 8h`
- Group : `client`, `server`
- Sprint: `Sprint__3__`
- Urgency: `High`
